[tasks.setup]
dependencies = [
  "brew-tap",
  "install-packages",
  "git-settings"
]

[tasks.brew-tap]
command = "brew"
args = ["tap", "hashicorp/tap", "homebrew/cask-fonts"]

[tasks.install-packages]
command = "brew"
args = [
  "install",
  "font-hack-nerd-font",
  "mise",
  "docker",
  "docker-compose",
  "hashicorp/tap/terraform"
]

[tasks.git-settings]
command = "./scripts/setting-git.sh"

[tasks.update-chrome]
command = "./scripts/update-chrome.sh"

[tasks.set-config]
dependencies = [
  "set-config-neovim",
  "set-config-ghostty",
  "set-config-mise"
]

[tasks.set-config-neovim]
command = "ln"
args = [
  "-s",
  "~/dotfiles/.config/nvim",
  "~/.config/nvim"
]

[tasks.set-config-ghostty]
command = "ln"
args = [
  "-s",
  "~/dotfiles/.config/ghostty",
  "~/.config/ghostty"
]

[tasks.set-config-mise]
command = "ln"
args = [
  "-s",
  "~/dotfiles/.config/mise",
  "~/.config/mise"
]
